### ISSUE TITLE
Typo in setup commands causes ./bashrc script to be overwritten, rather than appended to

### ISSUE THREAD

**Issue by rkabiljo** [dpuiu/MitoHPC#13]
This line must be a typo: 
echo "export HP_SDIR=`pwd`" > ~/.bashrc  

you probably wanted 
echo "export HP_SDIR=`pwd`" >> ~/.bashrc  

I ran it my mistake and deleted my ./bashrc, and that happened to another person I know who used it.  I won't do this again, of course, and should have noticed, but the best would be to fix the error.

Thank you

**Comment by dpuiu** [comment]
Hi Renata, you are right, that is a good catch! Thank you!

**Comment by rkabiljo** [comment]
Thank you
