### ISSUE TITLE
From Singularity container: haplogrep3 fails

### ISSUE THREAD

**Issue by rkabiljo** [dpuiu/MitoHPC#15]
Hello,
I am now in an environment where my only option is to run MitoHPC in a container.  When I do that, following your instructions, it all works fine until haplogrep, when it fails on:
 'Loading configuration from file 'haplogrep3.yaml' failed. Connection timed out'.

Any idea?  Thank you,
Renata

**Comment by rkabiljo** [comment]
Hello, I found out what the issue is. The environment I am running it in is Genomics England, and the issue is coming from their strict security settings: the haplogrep3.yaml file is pulling from a repository which is not whitelisted in their environment which causes the script to fail. Unfortunately they will not be able to whitelists this URL due to the data protection guidelines they have in place.  Would it be possible to run this pipeline in 'offline' mode? I am talking only about the singularity container, as even installing from GitHub is not something they allow me at the moment. Thank you,
Renata

**Comment by dpuiu** [comment]
Hi Renata, sorry about these issues and I am glad you found out what the problem was. 

The easiest way to test MitoHPC is by creating a simple(cheap) GoogleCloud instance and installing the repository over there. 

The Docker/Singularity images used the most up to date software (Haplogrep3,Gatk 4.4, java v19) and were not so extensively tested.

**Comment by rkabiljo** [comment]
Hi Daniela,
My problem lies precisely in the fact that in a very, very strict environment I am running this in, it will have to be your Singularity container.  I have tested MitoHPC from your GitHub, and it works well, but in order to incorporate it in a very important diagnostic pipeline, I am working under many security constrains, and this is one of them. The only way they will allow it is if it does not go to that haplogrep url from halpgrep3.yaml file.  Is there a way out of it?
Thank you,
Regards,
Renata

**Comment by rkabiljo** [comment]
Anything that does not go to an external URL would work. I would immensely appreciate it - it's the environment of Genomics England, that's why it's so strict!

**Comment by squigzzz** [comment]
I am having the same exact issue, except my security protocols are not as stringent and it kicks me out every few hundred requests since I am running thousands of samples through. Is there a way to download the yaml file locally and just supply it to haplogrep3 that way ?
