### ISSUE TITLE
Issues with chrMR.fa

### ISSUE THREAD

**Issue by munishika** [dpuiu/MitoHPC#5]
Hi,

I am using MitoHPC, however, I am getting following error:

A USER ERROR has occurred: Fasta index file file:///scratch/prj/mito_als/MitoHPC/RefSeq/chrMR.fa.fai for reference file:///scratch/prj/mito_als/MitoHPC/RefSeq/chrMR.fa does not exist. Please see http://gatkforums.broadinstitute.org/discussion/1601/how-can-i-prepare-a-fasta-file-to-use-as-reference for help creating it.

I have tried to build the .fai file, however, it doesn't work. Also the chrMR.fa file is empty. 

Can you please help me to figure out the issue.

Thanks in advance,
Munishika

**Comment by dpuiu** [comment]
Hi Munishika, sorry about that.  

I have updated  "scripts/circFasta.sh", the script which generates the "RefSeq/chrMR.fa" FASTA reference, along with the FASTA index file and now the GATK sequence dictionary. 

You have to rerun  "cd scripts/; . ./init.sh"

However "RefSeq/chrMR.fa"  should not be empty. 

Are you using the default HP_RNAME=hs38DH , HP_RMT=chrM , HP_MT=chrM variables?

**Comment by munishika** [comment]
Hi Daniela,

Thanks for your reply. 

I did rerun "cd scripts/; . ./init.sh"

I am using the default variables.

The chrMR.fa is definitely empty. Its also not present in the Github Refseq section (https://github.com/dpuiu/MitoHPC/tree/main/RefSeq), whilst all the other files are.

Any ideas how I can resolves this ?

**Comment by dpuiu** [comment]
Sorry, I forgot ... you also have to re-run  "./install_prerequisites.sh"

"install_prerequisites.sh" calls  "circFasta.sh" and "rotateFasta.sh" which generate the chrMC.* &  chrMR.* files

**Comment by munishika** [comment]
I did rerun "./install_prerequisites.sh" 
It creates chrMR file but it is empty:
>chrM

chrMR.fa (END)

**Comment by munishika** [comment]
Hi Daniela,

Thanks for your help previously.

I am still stuck with the same issue. I have followed all the steps that
you have mentioned, however, still no luck.

Looks like there is an issue with creating chrMR.fa and the files
corresponding to it. eg. the .fai, .dict etc.

Is there something I can do to fix the issue? I have tried everything, I
have also re-downloaded MitoHPC, just to be sure.

I really appreciate your help.

Best,
Munishika

Can you please

**Comment by dpuiu** [comment]
Hi Munishika,

Could you try running "rotateFasta.sh" manually?
This script has the -x flag set and will print out the commands and parameters.



cd scripts/
. ./init.sh
./rotateFasta.sh $HP_MT $HP_RDIR/$HP_MT $HP_E $HP_RDIR/$HP_MTR
ls -l $HP_RDIR/$HP_MTR.*




Daniela Puiu

Bioinformatics Engineer

Department of Biomedical Engineering

Johns Hopkins University

________________________________

**Comment by munishika** [comment]
Hi Daniela,

Thanks for your reply.

I followed your instructions, still no luck. Please find the output below:

(base) k2142499@erc-hpc-login2:/scratch/prj/mito_als/MitoHPC/scripts$ ./rotateFasta.sh $HP_MT $HP_RDIR/$HP_MT $HP_E $HP_RDIR/$HP_MTR
+ export N=chrM
+ N=chrM
+ export S=/scratch/prj/mito_als/MitoHPC/RefSeq//chrM
+ S=/scratch/prj/mito_als/MitoHPC/RefSeq//chrM
+ export E=300
+ E=300
+ SE=/scratch/prj/mito_als/MitoHPC/RefSeq//chrMR
+ test -s /scratch/prj/mito_als/MitoHPC/RefSeq//chrM.fa
+ test -s /scratch/prj/mito_als/MitoHPC/RefSeq//chrM.fa.fai
+ cat /scratch/prj/mito_als/MitoHPC/RefSeq//chrM.fa.fai
+ perl -ane 'print "$F[0]\t",$F[1]-$ENV{E},"\t$F[1]\n$F[0]\t0\t",$F[1]-$ENV{E},"\n";'
+ bedtools getfasta -fi /scratch/prj/mito_als/MitoHPC/RefSeq//chrM.fa -bed -
+ grep -v '>'
+ perl -ane 'BEGIN { print ">$ENV{N}\n" }  chomp; print ; END {print "\n"}'

Tool:    bedtools getfasta (aka fastaFromBed)
Version: v2.23.0
Summary: Extract DNA sequences into a fasta file based on feature coordinates.

Usage:   bedtools getfasta [OPTIONS] -fi <fasta> -bed <bed/gff/vcf> -fo <fasta> 

Options: 
	-fi	Input FASTA file
	-bed	BED/GFF/VCF file of ranges to extract from -fi
	-fo	Output file (can be FASTA or TAB-delimited)
	-name	Use the name field for the FASTA header
	-split	given BED12 fmt., extract and concatenate the sequencesfrom the BED "blocks" (e.g., exons)
	-tab	Write output in TAB delimited format.
		- Default is FASTA format.

	-s	Force strandedness. If the feature occupies the antisense,
		strand, the sequence will be reverse complemented.
		- By default, strand information is ignored.

	-fullHeader	Use full fasta header.
		- By default, only the word before the first space or tab is used.

+ samtools faidx /scratch/prj/mito_als/MitoHPC/RefSeq//chrMR.fa
[faidx] Could not build fai index /scratch/prj/mito_als/MitoHPC/RefSeq//chrMR.fa.fai

Any other suggestions??

**Comment by munishika** [comment]
Hi Daniela,

Thanks for getting  back to me. I used Bedtools version 2.23.0 (2021) and it did the trick.

Best,
Munishika
